[platformio]
default_envs = esp32s3dev-large

[env:esp32s3-common]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed = 921600
board_upload.flash_size = 16MB
board_build.partitions = default_16MB.csv
board_build.arduino.memory_type = qio_opi
board_build.psram_type = opi
build_flags =
    -DCORE_DEBUG_LEVEL=3
    -DBOARD_HAS_PSRAM
    -DARDUINO_USB_CDC_ON_BOOT=1
lib_deps =
    waspinator/AccelStepper @ ^1.64
    adafruit/Adafruit GFX Library @ ^1.11.11
    adafruit/Adafruit SSD1306 @ ^2.5.13
    adafruit/Adafruit SH110X @ ^2.1.13

[env:esp32s3dev-small]
extends = env:esp32s3-common
build_flags =
    ${env:esp32s3-common.build_flags}
    -DSTIRLING_OLED_DRIVER=STIRLING_OLED_DRIVER_SSD1306
    -DSTIRLING_OLED_HEIGHT=32

[env:esp32s3dev-large]
extends = env:esp32s3-common
build_flags =
    ${env:esp32s3-common.build_flags}
    -DSTIRLING_OLED_DRIVER=STIRLING_OLED_DRIVER_SH1106
    -DSTIRLING_OLED_HEIGHT=64
